### ISSUE TITLE
`kak-lsp` doesn't always send `workspace/didChangeConfiguration` server configuration options

### ISSUE THREAD

**Issue by razcore-rad** [kak-lsp/kak-lsp#654]
I noticed this only for `pyls`, configuration but might be more general.

From the log, seems that at some point `kak-lsp` stops sending the `initialize` `jsonrpc` method.

This means that `pyls` stops using the custom configuration options and reverts to defaults.

---

### `kak-lsp.toml` relevant section

```toml
[language.python]
filetypes = ["python"]
roots = [".git", "requirements.txt", "setup.py", "*.py"]
command = "pylsp"
workaround_server_sends_plaintext_labeled_as_markdown = true
settings_section = "_"
[language.python.settings._]
pylsp.configurationSources = ["flake8"]
pylsp.plugins.pycodestyle.enabled = false
pylsp.plugins.mccabe.enabled = false
pylsp.plugins.pyflakes.enabled = false
pylsp.plugins.flake8.enabled = true
pylsp.plugins.flake8.ignore = ["F821", "F722"]
pylsp.plugins.flake8.maxLineLength = 120
pylsp.plugins.black.line_length = 120
```

---

[kak-lsp.log](https://github.com/kak-lsp/kak-lsp/files/10145960/kak-lsp.log)

**Comment by krobelus** [comment]
I don't see a problem related to `initialize`.
This method is sent twice, both times with your custom configuration.
However there's a panic in your log, which I just fixed in c85c3e66e97a2fd2a14270df693bb76d0ec9c87d.
The panic is the reason for restarting the language server. Maybe that caused the issue although it should really not.
Let me know if it still reproduces / if you have steps to reproduce.

**Comment by razcore-rad** [comment]
Thanks, I'll get the update and check back if the problem persists.

**Comment by razcore-rad** [comment]
I haven't seen `pyls` losing configuration since the update so I'll close this issue for now. If anything changes I'll reopen.

**Comment by razcore-rad** [comment]
So something still happens where `pylsp` doesn't get configure correctly at times. So now because of the panic doesn't happen any more and the server isn't restarted it seems like the server configuration isn't reset in the middle of work, but instead it doesn't get configured at the start of the session at times.

This shows the configuration being default (e.g. ignoring my custom `maxLineLength`:

![image](https://user-images.githubusercontent.com/1177508/205487922-30982769-56f1-4913-b20c-91b9eb9693fb.png)

[kak-lsp.log](https://github.com/kak-lsp/kak-lsp/files/10148348/kak-lsp.log)

Might this be a `pylsp` problem instead?

**Comment by razcore-rad** [comment]
I looked at #655 and I see `kak-lsp` should send `workspace/didChangeConfiguration`which is missing in the log above. On the other hand this is a log where `pylsp` gets configured correctly:

[kak-lsp-works.log](https://github.com/kak-lsp/kak-lsp/files/10148357/kak-lsp.log)

**Comment by krobelus** [comment]
ok I can reproduce the problem with `maxLineLength` being ignored. We need to take a look at what keys pylsp expects because `pylsp.configurationSources = ["flake8"]` definitely works.
As a workaround, you can create this `tox.ini` which is more generally useful anyway.

```ini
[flake8]
max-line-length = 120
```

**Comment by razcore-rad** [comment]
Sure I know the workarounds, but that means that you'll have to use individual configurations for each plugin and I'd rather not, plus I like to have global configs. It's not just about `flake8`

**Comment by razcore-rad** [comment]
Also, I think it's `maxLineLength`, not `max-line-legth` in the `pylsp` plugin config.

**Comment by krobelus** [comment]
for me it fails even if the server does send `didChangeConfiguration`

I found the issue on my end: the warning comes from `pycodestyle`, not `flake8`

```json
      {
        "source": "pycodestyle",
        "range": {
          "start": {
            "line": 11,
            "character": 79
          },
          "end": {
            "line": 11,
            "character": 113
          }
        },
        "message": "E501 line too long (112 > 79 characters)",
        "code": "E501",
        "severity": 2
      },
```

so the fix for me is to use

```toml
pylsp.configurationSources = ["flake8"]
pylsp.plugins.pycodestyle.maxLineLength = 500
```

this works for me 100% of the time.

**Comment by krobelus** [comment]
> Sure I know the workarounds, but that means that you'll have to use individual configurations for each plugin and 

I think you can put config for all plugins into `tox.ini`. Probably the same goes for the flake8 equivalent.


> I'd rather not, plus I like to have global configs. It's not just about flake8

Maybe tox.ini supports global config or at least includes.

**Comment by krobelus** [comment]
if you can the scenario where we do not send `workspace/didChangeConfiguration`,
we should debug why `lsp-did-change-config` does not trigger (succeed)

**Comment by razcore-rad** [comment]
If you look at my first message in the issue, I already use `pylsp.configurationSources = ["flake8"]`, that's not the issue at my end.

**Comment by krobelus** [comment]
but I also need to use
`pylsp.plugins.pycodestyle.maxLineLength = 500` instead of 
`pylsp.plugins.flake8.maxLineLength = 500`

**Comment by razcore-rad** [comment]
O I see, I'll try that when I get the chance and come back to the issue

**Comment by razcore-rad** [comment]
Nope, I confirm that adding `pylsp.plugins.pycodestyle.maxLineLength` doesn't do anything for me. It just seems related to the fact that `kak-lsp` fails to send `workspace/didChangeConfiguration` sometimes for whatever reason.

[kak-lsp-fails.log](https://github.com/kak-lsp/kak-lsp/files/10148559/kak-lsp-fails.log)

**Comment by krobelus** [comment]
yeah that makes sense.
If you're motivated you could add log statements to `lsp-did-change-config` and if that is run also on the rust side where we call `workspace::did_change_configuration` etc.
This way we could figure out where things go wrong.
Maybe `lsp-did-change-config` never triggers, maybe it fails somewhere, etc.

**Comment by razcore-rad** [comment]
I can't really help with that, I haven't done anything rust-related otherwise I would have looked at the code already and I don't feel motivated enough to learn rust just for this issue :)

**Comment by krobelus** [comment]
no need to learn rust to add some log statements.
Anyway, I've been running kak with your config in a loop trying to reproduce this issue but after dozens of attempts it still didn't happen. Not sure how to reproduce, or how often it's supposed to occur.

**Comment by razcore-rad** [comment]
> ok I can reproduce the problem with `maxLineLength` being ignored. We need to take a look at what keys pylsp expects because `pylsp.configurationSources = ["flake8"]` definitely works. As a workaround, you can create this `tox.ini` which is more generally useful anyway.
> 
> ```ini
> [flake8]
> max-line-length = 120
> ```

That seems odd cause earlier I thought you could reproduce the `maxLineLength` issue, I thought of running a loop, but that wouldn't give me anything new in the logs so I just ran it a few times, e.g. `rm /tmp/kak-lsp.log && kak prop.py` until I got both successful and failed `pylsp` configurations.

I might try looking at the code a bit later if it doesn't look too difficult to get into. Thanks!

**Comment by razcore-rad** [comment]
Well I did try to add some logs, but the problem isn't in the `workspace::did_change_configuration` which makes sense cause it seems like when `pylsp` doesn't get configured the function doesn't get called altogether. `lsp-did-change-config` also seems to get triggered all the time so there seems to be something else in the chain that triggers the notification, it's just that I can't follow the code to understand where a problem might happen.

**Comment by krobelus** [comment]
ok that's good info already.
maybe something in `lsp-did-change-config` crashes - however this is very unlikely and can easily be refuted with some log statements:

```diff
diff --git a/src/controller.rs b/src/controller.rs
index e6157192..630fb0c0 100644
--- a/src/controller.rs
+++ b/src/controller.rs
@@ -97,6 +97,7 @@ pub fn start(
     'event_loop: loop {
         select! {
             recv(from_editor) -> msg => {
+                error!("FROM EDITOR: {:?}", msg);
                 if msg.is_err() {
                     break 'event_loop;
                 }
@@ -257,6 +258,7 @@ pub fn dispatch_pending_editor_requests(ctx: &mut Context) {
     let mut requests = std::mem::take(&mut ctx.pending_requests);
 
     for msg in requests.drain(..) {
+        error!("FROM EDITOR PENDING: {:?}", msg);
         dispatch_editor_request(msg, ctx);
     }
 }
```

each request that is sent from the editor to kak-lsp should pass through either of these log statements.
So by reproducing with this, we can narrow it down further. Eventually we can figure out where the request is lost.

Actually dispatch_editor_request() directly calls workspace::did_change_configuration, so the failing cases will not hit these log statements.. maybe the pending requests get lost somehow but that seems impossible as well.

**Comment by razcore-rad** [comment]
So I applied the patch and it looks like there's something happening in the loop, it receives error from the server or something. Anyway you have a better idea of what I can do next to debug further.

[kak-lsp-fails.log](https://github.com/kak-lsp/kak-lsp/files/10163615/kak-lsp-fails.log)

**Comment by krobelus** [comment]
the `Err(RecvError)` is unrelated and harmless, it happens only during shutdown, after the editor has quit.
This log shows that `workspace/didChangeConfiguration` never arrives.
This means that there must be something wrong with `lsp-did-change-config`.
Either it's never fired, or it somehow fails. Maybe add logging to that function to check if there is some problem in there.
For example, I'd replace `eval "${kak_opt_lsp_cmd} --request"` with a wrapper script that does the same thing except it also captures and logs its stdin.

**Comment by razcore-rad** [comment]
I added `tee`, but I don't see anything out of the ordinary. The hook triggers correctly it seems, even though the last run seems to not initialize properly.

```sh
# ...
) | tee ~/kak-lsp-did-change-config.log | eval "${kak_opt_lsp_cmd} --request") > /dev/null 2>&1 < /dev/null & }
```

The picture corresponds to the last log listing, but I don't see anything different compared to the other logs.

![image](https://user-images.githubusercontent.com/1177508/206645836-f3c16419-e916-484a-a0c7-7a171f2ad17e.png)

---
```fish
~ 
❯ bat kak-lsp-did-change-config.log 
         File: kak-lsp-did-change-config
     1   
     2   session  = "19192"
     3   client   = ""
     4   buffile  = "/home/razcore-rad/Projects/code/razcore-rad/blendercam/cam_refactor/props/__init__.py"
     5   filetype = "python"
     6   version  = 1
     7   method   = "workspace/didChangeConfiguration"
     8   hook = true
     9   [params.settings]
    10   lsp_config = """"""

~ 
❯ bat kak-lsp-did-change-config
         File: kak-lsp-did-change-config
     1   
     2   session  = "19603"
     3   client   = ""
     4   buffile  = "/home/razcore-rad/Projects/code/razcore-rad/blendercam/cam_refactor/props/__init__.py"
     5   filetype = "python"
     6   version  = 1
     7   method   = "workspace/didChangeConfiguration"
     8   hook = true
     9   [params.settings]
    10   lsp_config = """"""

~ 
❯ bat kak-lsp-did-change-config
         File: kak-lsp-did-change-config
     1   
     2   session  = "19946"
     3   client   = ""
     4   buffile  = "/home/razcore-rad/Projects/code/razcore-rad/blendercam/cam_refactor/props/__init__.py"
     5   filetype = "python"
     6   version  = 1
     7   method   = "workspace/didChangeConfiguration"
     8   hook = true
     9   [params.settings]
    10   lsp_config = """"""
```

**Comment by krobelus** [comment]
Ok that looks good. Then it can realy only be one thing, a transport error in the `${kak_opt_lsp_cmd} --request` process.
Can you log its stdout and stderr? Currently we can't tell if it panics etc.

**Comment by razcore-rad** [comment]
Yeah, so I changed the command to:
```sh
# ...
) | eval "${kak_opt_lsp_cmd} --request > ~/kak-lsp-did-change-config.log 2>&1") > /dev/null 2>&1 < /dev/null & }
```

and got this log:

```sh
~ 
❯ bat kak-lsp-did-change-config.log 
         File: kak-lsp-did-change-config.log
     1   Failed to daemonize process: LockPidfile(11)
```

But I don't know exactly how to debug further.

**Comment by krobelus** [comment]
thanks so much, this is a clear race condition.
Can you try the `fix-startup-race` branch and confirm that it's fixed?

**Comment by razcore-rad** [comment]
I tried `fix-startup-race` a few times, I haven't gotten the race condition so I'll let you close it with the fix I guess and if something changes I'll reopen the issue. Thanks a bunch :)
